# Generated by Django 5.1.3 on 2025-03-16 16:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest_template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default='2021-01-01')),
                ('end_date', models.DateField(default='9999-12-31')),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='23:59:59')),
                ('problems_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='User_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(default='staff', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.user_base'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
