# Generated by Django 5.1.3 on 2025-03-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_base',
        ),
    ]
