# Generated by Django 5.1.3 on 2025-03-16 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contest_template_user_base_alter_message_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_template',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
