# Generated by Django 5.1.3 on 2025-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_contest_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_template',
            name='end_date',
            field=models.DateField(default='9999-12-31'),
        ),
        migrations.AddField(
            model_name='contest_template',
            name='end_time',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AddField(
            model_name='contest_template',
            name='problems_id',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='contest_template',
            name='start_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='contest_template',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
