# Generated by Django 5.1.3 on 2025-05-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
