# Generated by Django 5.1.3 on 2025-06-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_contest_particpants_contest_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcontest',
            name='prizes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
