# Generated by Django 5.1.3 on 2025-05-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_particpants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_time', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='chat.scheduledcontest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participant', to='chat.users')),
            ],
            options={
                'unique_together': {('user_id', 'contest_id')},
            },
        ),
        migrations.CreateModel(
            name='contest_leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_solved_problem', models.JSONField()),
                ('reward_points', models.BigIntegerField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('contest_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participant', to='chat.contest_particpants')),
            ],
        ),
    ]
