# Generated by Django 5.1.3 on 2025-05-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_contest_particpants_contest_leaderboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest_particpants',
            old_name='user_id',
            new_name='user',
        ),
    ]
